### PR TITLE
Request new Merge

### PR DESCRIPTION
**Pull request by saltedlolly**
- Updated installbmlet.htlml with usage screenshots
- Progress bar in fetchtorrent.html
- Various rewording of text
- Updated readme

### CODE REVIEW

**Comment by bulljit** [comment]
Those .DS_Store files are causing me all kinds of headaches (Mac OS X adds them anytime you visit a folder in Finder.app therefore ours will never match up).

Can you run the following commands from your git folder in terminal:

```
find .-depth -name '.DS_Store'-exec git rm --cached '{}'\;-print
echo .DS_Store >> .gitignore
```

This will remove them from your repo, and then ignore them in the future

**Comment by saltedlolly** [comment]
I've actually done that already. I realized it was a problem, and googled it to find out how to fix it. I ran this earlier:

http://www.freshsauce.co.uk/tech+bits/git-ignore-dsstore-files-globally-per-user_28

I ran the command in the parent folder of the 'Transmission-Add-Torrent-Bookmarkelet' folder. Is this right? I am pretty sure it has worked since 'git status' no longer mentions the files, and they are no longer being included in my commits.... 

Sorry about that - this is my first time using Git & GitHub. A bit of a learning curve! I like it though, nice system. :)

**Comment by saltedlolly** [comment]
Incidentally, I was going to a few websites and forums about bookmarklets for Transmission and posting a link back to this site, when I came across these:

http://godsyn.com/bookmarklet/
http://crudtastic.com/uncategorized/setup-your-iphone-and-transmission-to-automatically-download-torrent-files/

I thought I might as well send them to you in case they are useful. 

Also, I was thinking about the username / password for accessing the webui. When it is enabled in Transmission, you need to enter the username and password when you ever you load the bookmarklet which some users might find annoying after a while. What are your thoughts are on the idea of modifying the form to optionally include the username and password in the bookmarklet. The second link above talks about it. Is that very insecure? What do you think?

Last question, do you have any way of knowing if anyone else has tried this out? Do they keep stats of the number of downloads from GitHub. I'm just curious...

**Comment by bulljit** [comment]
The godsyn  and crutastic versions will no longer work, due to the requirement of a session-id. That's why all those other examples in the TSM forums failed.  And unfortunately why we have all this server-side code going on in our version.

I finally made it through boxee's method and unfortunately they use server-side scripting (php) which I can't implement unless the end-user wants to learn how to set up their own webserver.  Basically you're trusting boxee.tv with information you send them, which I doubt people will be so willing to do with torrents, if I were to set up a similar website.

I'll look into the downloads stat thing...

**Comment by saltedlolly** [comment]
I really don't understand why the fetchtorrent.html file takes so long to download the torrent. Even accessing Transmission from my phone over WiFi still takes 30-60 seconds to report 'success'. EDGE I am getting 90-120 seconds. Is this a server issue? What are your experiences? My home internet is pretty slow it must be said. 1Mbps connection. In reality much less.

**Comment by bulljit** [comment]
It actually doesn't download the torrent. It only passes the information on to your Transmission.app. And then waits for a reply message. Speed issues will be dependent on your home computers connection.

**Comment by bulljit** [comment]
Just tested on 3G with iPhone, only takes about 3 secs.

**Comment by saltedlolly** [comment]
Okay it must be my Transmission install. Interestingly I tested it via the browser on my laptop over the LAN and it was fast to download. The delay only happens on my phone. Weird.

PS I updated the Wiki as requested with more general instructions. I decided the Wiki could explain everything, whereas the readme just covers the bookmarklet itself.

PPS I came across this: https://addons.mozilla.org/en-US/firefox/addon/13854/ - doesn't seem to work though.

**Comment by bulljit** [comment]
Have you tested it on your phone but using your LAN instead of EDGE.  I've never been in an area with only EDGE, but i assume if it's slower than your home computer's upload speed, then that may be your bottleneck as well.

That is the reason I decided to have transmission do all the heavy lifting (downloading the torrent file).  A working safari extension was created: 

https://forum.transmissionbt.com/viewtopic.php?f=1&t=11224&hilit=safari

But in his setup the client downloads the torrent, then uploads the data to transmission, lots of bandwith usage that way.

Thanks for your efforts so far, I really do appreciate it.  I added you as a "collaborator." Does that give you full access to change my source?

**Comment by saltedlolly** [comment]
I will try it. I think so.

**Pull request merged**
