### PR TITLE
Install Bookmarklet Page - What I have so far

### PR DESCRIPTION
**Pull request by saltedlolly**
I finally managed to upload what I have done so far. I simply modified an existing page. The screenshots are just place holders for now. Can't do the rest until it is actually working. This is about as far as I can go. It took me long enough just trying to figure out how to use Git, not to mention having to remember how to use VI - it's been years!

My idea is that you link to this page somehow from the footer of the iphone webui. Is this possible?

This is not yet ready for prime time but maybe you can get it there!

Hope this helps!

### CODE REVIEW

**Comment by bulljit** [comment]
nice work with the screen shots!

**Comment by bulljit** [comment]
I think my approach will be to serve a separate website from which to install the bookmarklet.  It will contain:

Input boxes:
1. IP of server (default to visitor's ip)
2. Port number (default to 9091)

Button:
- when clicked it will output a dummy link: www.mywebsite.com/remove.this.html?javascript..... which contains the inputed ip and port

The user can then click the link, add the bookmark, and remove the crap before javascript: in the url.

Are we talking about the same topic? :)

**Comment by saltedlolly** [comment]
Yes. :) Take a look at the installbmlet.html file and you will see what I mean. This file can be put wherever on the users Transmission install. Then link to it from the webui page somewhere.

I can help you by doing the rest of the screenshots once it is possible to link to the page. :)

Hope I am helping more than hindering! :)

**Comment by bulljit** [comment]
Ok i added the coding for a very basic install page "fetchtorrent_help.html." Again just add it to your transmission/web folder.

Later I will add a link to the main fetchtorrent.html page to refer to the above.

Can you:
1. test for bugs
2. spice it up with your screen shots and purty colors

**Comment by saltedlolly** [comment]
Not sure why my notes weren't added to my first commit but I have updated the HTML and made it all look pretty, as well as adding the other screenshots. It all works okay for me, but you might want to test it yourself. Quite slick in the end with your Javascript. I wish I knew that stuff! :)

**Comment by bulljit** [comment]
Fantastic work!

I'm new to github too, this is kinda fun, hahaha.

Feel free to fork the WIKI and update that too _hint_hint*

**Comment by saltedlolly** [comment]
I guess the other things that could be done would be to add support for private trackers somehow. I read somewhere that it involves adding a cookies.txt file into your Transmission config directory. Not sure how to proceed with that. It's your area!

One other suggestion would be to add a spinning progress image to the fetchtorrent.html file to display while it is loading the Torrent. It would make it clearer that something is still happening. Also there seems to be an issue with wrapping the text in the name of the Torrent file. It sometimes strays outside the box.

One other thought, is that I was wondering if it is actually necessary to open a new page? Check out how the Boxee Bookmarklet works. Very slick: http://www.boxee.tv/watchlater

**Comment by bulljit** [comment]
looks like you've already taken care of the "progress bar."

The boxee idea is slick!  But the associated code is about 600 lines, so it's going to take me some time to muddle through it.

I'm going to split the discussion about "private torrents" into a separate issue to keep this more organized.

**Comment by bulljit** [comment]
fixed the text wrapping :) i think...

**Comment by saltedlolly** [comment]
I made  few updates which need to pushed back into your code.

**Pull request closed without merging**
